---
title: 흐림없이 맑은 눈
author: 장운호
date: '2018-05-27'
slug: 흐림없이-맑은-눈
categories:
  - R
tags:
  - R Markdown
---

기분 좋게 하루를 시작했는데, 어제까지 잘되던 키보드가 먹통이 되었다.
액토라는 회사의 2.4G Hz 키보드였는데, 휴렛팩커드의 ENVY 노트북에 USB포트 연장해서 쓰고 있어서, 중국산 제품의 수명이 다한지 알고, 그래 바꿀 때도 되었지, 하고 마트에 가서 키보드를 보니, 값들이 인터넷에서 사는 것과는 차이가 많아서, 일단 업무만 처리하면 되지 하고, 가장 저렴하고, 기본적인 기능은 할 것 같은 중원전자라는 회사의 LUCAS라는 회사의 유선 키보드를 구매했다.

근데, 이것도 안된다. 키보드 박스에 전화번호가 있어, 전화를 하고, 모델명을 이야기하니 그 제품은 품절이라고 한다. 그래서 방금 마트에서 샀다고 했더니, 그럼 거기에 가보란다. 거리가 조금 되어서, 안되는 이유를 묻고싶다고 했더니, 여기는 AS센터가 아니고 물건이 무슨 문제가 있는지 직접 확인할 수 없으니, 안된단다. 그래서 중원전자에서 만든게 아니냐 했더니, 만든 것 맞고, 판매한 것도 맞는데, 여기는 AS센터가 아니라 아무것도 답변해 주지 못한단다.

허 이것 참, 아침부터 싸울 수도 없고, 일단 대범하게 마트로 가서 이게 안된다고 했더니, 왜 안되냐고 한다. 상품박스에 적힌 전화번호로 전화를 했더니, 이러저러한 이야기를 하더라고 의심나면 전화해 보시라고 하니, 거기에 전화할 정도까지는 아니라고 하신다. 마침 주임님이 지나가신다면서, 환불을 해도 되냐고 묻고, 쿨하게 환불해 주셔서, 진짜로 걱정되는 마음에 매대에 5개 인가 남아 있었다고, 물건이 잘못되었으니, 매대에서 내리는 게 좋다고 하니, 계산하시는 아주머니와 떠꺼머리 총각 주임이 눈빛을 맞추고 나서 보일듯 말듯 웃으며, 카드나 주세요. 환불해 드릴테니, 하더니 정확히 환불전표를 내 주신다.

그래서 오늘은 일이 안될 것 같아서, 사무실에 다시 왔다가,,, (허참 무슨 왔다리 갔다리도 아니고…) 월요일에는 강의자료를 올려주어야 할 것 같은데, 그래도 오늘은 마무리 해야지 하면서, 그래 백화점에서 사면 되겠지 하고 백화점에서 LG 키보드를 그것도 가장 확실한 유선으로 사왔다.

근데, 이것도 안된다.

이 때, 깨달았다. 키보드 잘못이 아니었구나…..

그래서 마이크로 소프트에 전화를 했다. 상냥한 여직원에게 사정을 이야기 하니, 삼성키보드하고 마우스가 안된다는 이야기를 들었다고 하면서, 제어판에가서 업데이트 제거를 하라고 한다. 안보인다고 했더니, 기술지원으로 연결을 해준다. 돌려달라고 했더니, 안된다고 하면서, 친절하게 연결방법을 알려준다. 그래서 전화를 했더니, 확실히 기술지원담당이라, 바로 찾아갈 수 있게 해주면서, 그거를 취소하라고 한다. 그래서 취소를 하면서 아무 생각없이, 이것 때문인가요? 했더니, 아니란다. 요새는 개인별 컴퓨터 환경이 틀리고, 고장은 원래 어제 잘 되다가도 오늘 안되는 것이라면서, 변호사 법률자문을 거친 답변을 한다.

이정도면, 상당히 잘 교육을 하긴 하는 것 같다고 생각하며, 기다리고 있는데, 고객님 전화요금이 걱정되어, 일단 끊겠다고 한다. 내가 오늘 이것 때문에 소비한 시간이 거의 몇시간인데, 몇분정도는 괜찮고, 요금제도 무제한이라 상관없다면서, 그냥 편하게 계시라고 하면서, 아이유의 모던 타임즈를 틀었다.

채플린 노래가 다 끝날 때쯤, 무슨 변화가 있냐길래, 없다고 했더니, 취소하고 리부팅을 해보란다. 업데이트를 하면서 %표시가 막 올라가는데, 이것도 시간이 걸려, 기다리면서 또 아이유의 모던 타임즈를 들으니, 리부팅이 완료되고, 드뎌, 다시 키보드가 먹는다. 이것 때문에 오늘 몇군데 나 한테, 정중하게 싫은 소리를 들었다고 했더니, 다음부터는 자기네한테 먼저 연락하란다.

그래서 나한테 이래라 저래라 하지마라. 나는 마이크로소프트가 잘못하리라는 생각을 하지도 못했다. 다른 분들에게 정말 죄송하다고 했더니, 이래라 저래라 한 것이 아니라, 자기는 서비스 안내를 했다고 한다. 그래서 서비스 하시는 분은 서비스만 하시면 되지만, 제품을 잘 만들면 이런 일이 없었을 것 같다고 하니, 알았다고 한다.

정말 미안하다. 중원전자 그 친구에게. 그런 전화를 많이 받았는지, 태도가 전투적이었다. 하지만, 물러날 때를 알고, 참을 인(忍) 세개를 마음에 새긴 덕에, 잘못한 회사가 아닌 다른 사람들에게 실수를 하지 않은 것이 다행이라는 생각이 들었다.

왜, 마이크로 소프트가 잘못했다고는 생각조차 하지 않았을까????
걔들도 똑 같은 회사이고, 실수할 수 있는 조직인데 말이다.
겸허한 마음과 흐림없이 맑은 눈이 필요한 세상에 살고 있는 중이기 때문이 아닐까?

그래서 미안한 마음에 마트를 다시갔다 왔다. 잘된다. 중원전자 LUCAS, ㅎㅎㅎㅎㅎ